export enum ActionTypes {
    ADDUSER="ADDUSER",
    REMOVEUSER="REMOVEUSER",
    ADD_TOAST_REF="ADD_TOAST_REF",
    SET_IS_LOADING="SET_IS_LOADING",
    SET_IS_NOT_LOADING="SET_IS_NOT_LOADING",
    SET_ACTIVE_DEBATE="SET_ACTIVE_DEBATE",
    REMOVE_ACTIVE_DEBATE="REMOVE_ACTIVE_DEBATE",
    SET_UPCOMING_DEBATE_TAB = "SET_UPCOMING_DEBATE_TAB",
    SET_LIVE_DEBATE_TAB = "SET_LIVE_DEBATE_TAB",
    SET_IS_USER_PARTICIPANT="SET_IS_USER_PARTIPANT",
    SET_IS_LIVE= "SET_IS_LIVE"
}
